### PR TITLE
Add NL parsing rules

### PR DESCRIPTION
**Pull request by Pitchiu**
This PR adds parsing rules for the Netherlands.

### CODE REVIEW

**Comment by Pitchiu** [comment]
@norgevz could you take a look?

**Review by skyman503 — CHANGES_REQUESTED** [review]
Shouldn't there be some sort of separator between the building and unit? I found and example where the address was  32-6 and proposed change would use it as 326 which seems wrong.

**Comment by Pitchiu** [comment]
> Shouldn't there be some sort of separator between the building and unit? I found and example where the address was 32-6 and proposed change would use it as 326 which seems wrong.

Correct, let's use hyphen since there is no hard rule for that in NL.

**Comment by Pitchiu** [comment]
@skyman503, @norgevz suggestions applied. PR ready for the review.

**Review by norgevz — APPROVED** [review]
LGTM!

**Pull request merged**
